number_of_qubits: 5
hidden_layer_dimension: 10
ising_activation: 1
magnetic_field_coupling_strength: 1
number_of_training_iterations: 200
number_of_training_samples: 1000
learning_rate: 0.005
device: "cpu"